"""
src/preprocessing/pipeline.py

Glue code for the preprocessing flow:

cleaner -> language -> abbreviations -> embeddings

Input:
    list[dict] records

Output:
    candidate pairs generated by the embeddings stage

T:contentReference[oaicite:0]{index=0}nally flexible so it can work with slightly different
function/class names in the teammate-built modules.
"""

from __future__ import annotations

from typing import Any, Callable, Iterable, Sequence


class PreprocessingPipeline:
    """
    Orchestrates the preprocessing stages in order:

    1. cleaner
    2. language
    3. abbreviations
    4. embeddings

    The first three stages are expected to transform the record list.
    The final embeddings stage is expected to return candidate pairs.
    """

    def __init__(
        self,
        cleaner_module: Any | None = None,
        language_module: Any | None = None,
        abbreviations_module: Any | None = None,
        embeddings_module: Any | None = None,
    ) -> None:
        if cleaner_module is None:
            from src.preprocessing import cleaner as cleaner_module
        if language_module is None:
            from src.preprocessing import language as language_module
        if abbreviations_module is None:
            from src.preprocessing import abbreviations as abbreviations_module
        if embeddings_module is None:
            from src.preprocessing import embeddings as embeddings_module

        self.cleaner = cleaner_module
        self.language = language_module
        self.abbreviations = abbreviations_module
        self.embeddings = embeddings_module

    def run(self, records: Sequence[dict[str, Any]]) -> Any:
        """
        Run the full preprocessing pipeline.

        Args:
            records: A list of input records.

        Returns:
            Candidate pairs produced by the embeddings stage.
        """
        if records is None:
            raise ValueError("records cannot be None")

        current_records = list(records)

        current_records = self._run_cleaner(current_records)
        current_records = self._run_language(current_records)
        current_records = self._run_abbreviations(current_records)

        candidate_pairs = self._run_embeddings(current_records)
        return candidate_pairs

    __call__ = run

    def _run_cleaner(self, records: Sequence[dict[str, Any]]) -> Any:
        return self._call_stage(
            stage=self.cleaner,
            method_names=[
                "clean_records",
                "clean",
                "process",
                "run",
                "transform",
            ],
            data=records,
            stage_name="cleaner",
        )

    def _run_language(self, records: Sequence[dict[str, Any]]) -> Any:
        return self._call_stage(
            stage=self.language,
            method_names=[
                "detect_languages",
                "annotate_language",
                "detect",
                "process",
                "run",
                "transform",
            ],
            data=records,
            stage_name="language",
        )

    def _run_abbreviations(self, records: Sequence[dict[str, Any]]) -> Any:
        return self._call_stage(
            stage=self.abbreviations,
            method_names=[
                "expand_abbreviations",
                "normalize_abbreviations",
                "expand",
                "process",
                "run",
                "transform",
            ],
            data=records,
            stage_name="abbreviations",
        )

    def _run_embeddings(self, records: Sequence[dict[str, Any]]) -> Any:
        return self._call_stage(
            stage=self.embeddings,
            method_names=[
                "generate_candidate_pairs",
                "build_candidate_pairs",
                "candidate_pairs",
                "embed_and_block",
                "process",
                "run",
                "transform",
            ],
            data=records,
            stage_name="embeddings",
        )

    @staticmethod
    def _call_stage(
        stage: Any,
        method_names: list[str],
        data: Any,
        stage_name: str,
    ) -> Any:
        """
        Calls a stage using the first matching callable interface it exposes.

        Supported patterns:
        - stage(data)                        if stage itself is callable
        - stage.some_method(data)            if a known method exists
        """
        # If the imported stage itself is directly callable, use it.
        if callable(stage):
            return stage(data)

        # Otherwise try common method names.
        for method_name in method_names:
            method = getattr(stage, method_name, None)
            if callable(method):
                return method(data)

        available = [
            name for name in dir(stage)
            if not name.startswith("_") and callable(getattr(stage, name, None))
        ]

        raise AttributeError(
            f"Could not find a callable entry point for '{stage_name}'. "
            f"Tried methods: {method_names}. "
            f"Available callables: {available}"
        )


def run_pipeline(records: Sequence[dict[str, Any]]) -> Any:
    """
    Convenience function for running the default pipeline.
    """
    pipeline = PreprocessingPipeline()
    return pipeline.run(records)

